### PR TITLE
Checkout branch

### PR DESCRIPTION
**Pull request by selena92**
Took Rigshan's file and finished it (selecting dropdown box, shipping method and payment)

### CODE REVIEW

**Review by Rigshan — APPROVED** [review]
file is looking good, all set to merge in my opinion

**Comment by tuhelahmed98** [comment]
Perfect you're definitely ready to merge :)

**Review by tuhelahmed98 — APPROVED** [review]
Great work ready to merge:)

**Comment by Rigshan** [comment]
all good - well done :0

**Pull request merged**
